---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tunnel-operator-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tunnel-operator-manager-role
rules:
  - apiGroups:
      - net.liqo.io
    resources:
      - tunnelendpoints
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - net.liqo.io
    resources:
      - tunnelendpoints/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - events
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tunnel-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tunnel-operator-manager-role
subjects:
  - kind: ServiceAccount
    name: tunnel-operator-service-account
    namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: tunnel-operator
  name: tunnel-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      run: tunnel-operator
  strategy: {}
  template:
    metadata:
      labels:
        run: tunnel-operator
        net.liqo.io/gatewayPod: "true"
    spec:
      nodeSelector: 
        net.liqo.io/gateway: "true"
      serviceAccountName: tunnel-operator-service-account
      containers:
        - image: {{ .Values.tunnelEndpointOperator.image.repository }}{{ .Values.global.suffix | default .Values.suffix }}:{{ .Values.global.version | default .Values.version }}
          imagePullPolicy: {{ .Values.tunnelEndpointOperator.image.pullPolicy }}
          name: tunnel-operator
          ports:
          - containerPort: 5871
          command: ["/usr/bin/liqonet"]
          resources:
            limits:
              cpu: 10m
              memory: 30M
            requests:
              cpu: 10m
              memory: 30M
          securityContext:
            privileged: true
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOCAL_TUNNEL_PUBLIC_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      hostNetwork: false
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: wireguard-endpoint
  labels:
    net.liqo.io/tunnelEndpoint: "true"
spec:
  type: NodePort
  ports:
    - name: wireguard
      port: 5871
      targetPort: 5871
      protocol: UDP
  selector:
    net.liqo.io/gatewayPod: "true"