name: Add the ok-to-test label
on:
  repository_dispatch:
    types:
      - ok-to-test-command

jobs:
  automerge:
    name: Merge
    runs-on: ubuntu-latest

    steps:
      - name: Add the merge-requested label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: "${{ secrets.CI_TOKEN }}"
          number: ${{ github.event.client_payload.github.payload.issue.number }}
          labels: ok-to-test
